version: '3.8'

services:
  backend-pub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5148:5148" # Mapea el puerto HTTP
      - "7108:7108" # Mapea el puerto HTTPS (si es necesario)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5148
    networks:
      - my_network # Red para comunicación con otros contenedores

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # Puerto para RabbitMQ
      - "15672:15672" # Puerto para RabbitMQ Management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
